### ISSUE TITLE
style.css file is not included anymore

### ISSUE THREAD

**Issue by gaetan-petit** [yoarts/flat#80]
**version**: 1.5.6
**description**:
As of version 1.5.6 the style.css fil is not included anymore.

**Comment by BrazenlyGeek** [comment]
That was intentional to eliminate the HTTP request for it. The file doesn't contain any actual styling, as all of it is included via a minified file stored in a subdirectory.

Is there a particular reason why you would need `style.css` to be included?

**Comment by thanhluu** [comment]
@BrazenlyGeek I think we need to including `style.css` to the base theme after `flat.css` has been loaded. It will be helpful when we create a child theme of flat.

@gaetan-petit I have added back `style.css` to Flat 1.5.7 and It is being review on WP.org

**Comment by BrazenlyGeek** [comment]
Given that most users will be using Flat w/o a child theme, including `style.css` is a wasted HTTP request.

There's nothing in the file a child theme needs -- and a child theme has to have its own `style.css` to be recognized by WordPress anyway.

I'm not sure what advantage including a blank `style.css` has.

If the idea is to provide a shortcut to ensure that a child theme's style is included, a conditional would ensure we're not wasting an HTTP request if the base theme is used:

`if ( STYLESHEETPATH != TEMPLATEPATH ) {
	wp_enqueue_style( 'flat-style', get_stylesheet_uri(), array(), $version );
}`

But then that assumes that the child theme has styles that need included rather than simply providing custom templates or `functions.php` customizations.

My vote is that Flat only includes the `flat.css` styling rather than assuming anything about `style.css` (especially blank ones).
